[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bc9298fa70e9831bbab65e2fba6afbf0c9bfc9e"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "70da9a3a43aa866591cea0ef258d200682c14d4f6ac5f53f958b92c6a897dc23"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55ed6264fc9b7417eadec211cf3b0c656b426602"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "f28946274685efce5faf4acc2fddbd09b5dc56dccadc955c07d87cab4ec31e94"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e017cb6d9e41eb922ac3bfd3fa45df8eab6e6b6e"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "31354c3f83b393a86b04fe9a1f8563fe803f403829da7c29705e699c37b25614"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.2-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8cb30ee3e3936cecb3299c34b21310a93ce52ad"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "7e2fb40ba68c0a26965127b91eaf2738617cb7afce006edc116c7f325f03423f"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.2-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e017cb6d9e41eb922ac3bfd3fa45df8eab6e6b6e"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "31354c3f83b393a86b04fe9a1f8563fe803f403829da7c29705e699c37b25614"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.3-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8cb30ee3e3936cecb3299c34b21310a93ce52ad"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "7e2fb40ba68c0a26965127b91eaf2738617cb7afce006edc116c7f325f03423f"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.3-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e017cb6d9e41eb922ac3bfd3fa45df8eab6e6b6e"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "31354c3f83b393a86b04fe9a1f8563fe803f403829da7c29705e699c37b25614"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.4-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8cb30ee3e3936cecb3299c34b21310a93ce52ad"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "7e2fb40ba68c0a26965127b91eaf2738617cb7afce006edc116c7f325f03423f"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.4-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e017cb6d9e41eb922ac3bfd3fa45df8eab6e6b6e"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "31354c3f83b393a86b04fe9a1f8563fe803f403829da7c29705e699c37b25614"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.5-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8cb30ee3e3936cecb3299c34b21310a93ce52ad"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "7e2fb40ba68c0a26965127b91eaf2738617cb7afce006edc116c7f325f03423f"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.5-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e017cb6d9e41eb922ac3bfd3fa45df8eab6e6b6e"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "31354c3f83b393a86b04fe9a1f8563fe803f403829da7c29705e699c37b25614"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.6-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8cb30ee3e3936cecb3299c34b21310a93ce52ad"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "7e2fb40ba68c0a26965127b91eaf2738617cb7afce006edc116c7f325f03423f"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.6-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e017cb6d9e41eb922ac3bfd3fa45df8eab6e6b6e"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "31354c3f83b393a86b04fe9a1f8563fe803f403829da7c29705e699c37b25614"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.8-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8cb30ee3e3936cecb3299c34b21310a93ce52ad"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "7e2fb40ba68c0a26965127b91eaf2738617cb7afce006edc116c7f325f03423f"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.0+1/cunumeric_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.8-julia_version+1.11.1.tar.gz"
