[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bc9298fa70e9831bbab65e2fba6afbf0c9bfc9e"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "70da9a3a43aa866591cea0ef258d200682c14d4f6ac5f53f958b92c6a897dc23"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.1+0/cunumeric_jl_wrapper.v25.10.1.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55ed6264fc9b7417eadec211cf3b0c656b426602"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "f28946274685efce5faf4acc2fddbd09b5dc56dccadc955c07d87cab4ec31e94"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.1+0/cunumeric_jl_wrapper.v25.10.1.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97b9cff1b6fb58ddb2130b3b1f9619724f9a7691"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "44f493a63788055b37e8dbf7b17553e90e5ac93c2c7e9f77f77d6b6575857019"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.1+0/cunumeric_jl_wrapper.v25.10.1.x86_64-linux-gnu-cxx11-cuda+13.0-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fae9853a4a9c50a655c6205f50ee395e07e843df"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "f3a2ea774cc1aaa08ccdeefbbc787f13d0994ff65334d4e32dff544f44cc1e04"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v25.10.1+0/cunumeric_jl_wrapper.v25.10.1.x86_64-linux-gnu-cxx11-cuda+13.0-julia_version+1.11.1.tar.gz"
